// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py
@file:Suppress("MaxLineLength")

package com.hp.jipp.model

import com.hp.jipp.encoding.Enum
import com.hp.jipp.encoding.EnumType

/**
 * "print-quality" enum as defined in
 * [RFC8011](http://www.iana.org/go/rfc8011)
 */
data class PrintQuality(override val code: Int, override val name: String) : Enum() {

    override fun toString() = super.toString()

    /** An attribute type for [PrintQuality] attributes */
    class Type(name: String) : EnumType<PrintQuality>(Encoder, name)

    object Code {
        const val draft = 3
        const val normal = 4
        const val high = 5
    }

    companion object {
        @JvmField val draft = PrintQuality(Code.draft, "draft")
        @JvmField val normal = PrintQuality(Code.normal, "normal")
        @JvmField val high = PrintQuality(Code.high, "high")

        @JvmField val Encoder = EnumType.Encoder(PrintQuality::class.java) { code, name ->
            PrintQuality(code, name)
        }
    }
}
