// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.KeywordOrName
import com.hp.jipp.encoding.KeywordType
import com.hp.jipp.encoding.Tag

/**
 * "coating-type" keyword as defined in:
 *   * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
 *
 * Also used by:
 *   * `coating-type-supported`
 */
data class CoatingType(
    override val value: String,
    override val tag: Tag = Tag.keyword,
    override val language: String? = null
) : KeywordOrName() {

    constructor(value: String): this(value, Tag.keyword)

    override fun toString() = value

    /** An attribute type for [CoatingType] attributes */
    class Type(name: String) : KeywordType<CoatingType>(Encoder, name)

    companion object {
        @JvmField val archival = CoatingType("archival")
        @JvmField val archivalGlossy = CoatingType("archival-glossy")
        @JvmField val archivalMatte = CoatingType("archival-matte")
        @JvmField val archivalSemiGloss = CoatingType("archival-semi-gloss")
        @JvmField val glossy = CoatingType("glossy")
        @JvmField val highGloss = CoatingType("high-gloss")
        @JvmField val matte = CoatingType("matte")
        @JvmField val semiGloss = CoatingType("semi-gloss")
        @JvmField val silicone = CoatingType("silicone")
        @JvmField val translucent = CoatingType("translucent")
        @JvmField val Encoder = KeywordType.encoderOf(CoatingType::class.java) { value, tag, language ->
            CoatingType(value, tag, language)
        }
    }
}
