// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "cover-back-supported" keyword as defined in
 * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf).
 *
 * Also used by:
 *   * `cover-front-supported`
 *   * `job-cover-back-supported`
 */
data class CoverBackSupported(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [CoverBackSupported] attributes */
    class Type(name: String) : KeywordType<CoverBackSupported>(Encoder, name)

    companion object {
        @JvmField val coverType = CoverBackSupported("cover-type")
        @JvmField val media = CoverBackSupported("media")
        @JvmField val mediaCol = CoverBackSupported("media-col")
        @JvmField val Encoder = KeywordType.encoderOf(CoverBackSupported::class.java) { value, _, _ ->
            CoverBackSupported(value)
        }
    }
}
