// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "document-format-varying-attributes" keyword as defined in:
 *   * [RFC3380](http://www.iana.org/go/rfc3380)
 */
data class DocumentFormatVaryingAttribute(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [DocumentFormatVaryingAttribute] attributes */
    class Type(name: String) : KeywordType<DocumentFormatVaryingAttribute>(Encoder, name)

    companion object {
        @JvmField val none = DocumentFormatVaryingAttribute("none")
        @JvmField val Encoder = KeywordType.encoderOf(DocumentFormatVaryingAttribute::class.java) { value, _, _ ->
            DocumentFormatVaryingAttribute(value)
        }
    }
}
