// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "document-format-details-supported" keyword as defined in:
 *   * [PWG5100.7](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext10-20031031-5100.7.pdf)
 */
data class DocumentFormatDetails(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [DocumentFormatDetails] attributes */
    class Type(name: String) : KeywordType<DocumentFormatDetails>(Encoder, name)

    companion object {
        @JvmField val documentFormat = DocumentFormatDetails("document-format")
        @JvmField val documentFormatDeviceId = DocumentFormatDetails("document-format-device-id")
        @JvmField val documentFormatVersion = DocumentFormatDetails("document-format-version")
        @JvmField val documentNaturalLanguage = DocumentFormatDetails("document-natural-language")
        @JvmField val documentSourceApplicationName = DocumentFormatDetails("document-source-application-name")
        @JvmField val documentSourceApplicationVersion = DocumentFormatDetails("document-source-application-version")
        @JvmField val documentSourceOsName = DocumentFormatDetails("document-source-os-name")
        @JvmField val documentSourceOsVersion = DocumentFormatDetails("document-source-os-version")
        @JvmField val Encoder = KeywordType.encoderOf(DocumentFormatDetails::class.java) { value, _, _ ->
            DocumentFormatDetails(value)
        }
    }
}
