// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "finishings-col-supported" keyword as defined in:
 *   * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
 *
 * Also used by:
 *   * `job-finishings-col-supported`
 */
data class FinishingsCol(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [FinishingsCol] attributes */
    class Type(name: String) : KeywordType<FinishingsCol>(Encoder, name)

    companion object {
        @JvmField val finishingTemplate = FinishingsCol("finishing-template")
        @JvmField val stitching = FinishingsCol("stitching")
        @JvmField val Encoder = KeywordType.encoderOf(FinishingsCol::class.java) { value, _, _ ->
            FinishingsCol(value)
        }
    }
}
