// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "identify-actions" keyword as defined in:
 *   * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
 *
 * Also used by:
 *   * `identify-actions-default`
 *   * `identify-actions-supported`
 */
data class IdentifyActions(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [IdentifyActions] attributes */
    class Type(name: String) : KeywordType<IdentifyActions>(Encoder, name)

    companion object {
        @JvmField val display = IdentifyActions("display")
        @JvmField val flash = IdentifyActions("flash")
        @JvmField val sound = IdentifyActions("sound")
        @JvmField val speak = IdentifyActions("speak")
        @JvmField val Encoder = KeywordType.encoderOf(IdentifyActions::class.java) { value, _, _ ->
            IdentifyActions(value)
        }
    }
}
