// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "insert-sheet" collection as defined in:
 * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf),
 * [RFC8011](http://www.iana.org/go/rfc8011).
 */
@Suppress("RedundantCompanionReference", "unused")
data class InsertSheet
@JvmOverloads constructor(
    val insertAfterPageNumber: Int? = null,
    val insertCount: Int? = null,
    val media: Media? = null,
    val mediaCol: MediaCol? = null,
    val _extras: List<Attribute<*>> = listOf()
) : HasAttributeCollection {

    /** Generate attribute list */
    override val attributes: AttributeCollection by lazy {
        AttributeCollection(mutableListOf<Attribute<*>>().apply {
            insertAfterPageNumber?.also {
                add(Members.insertAfterPageNumber.of(it))
            }
            insertCount?.also {
                add(Members.insertCount.of(it))
            }
            media?.also {
                add(Members.media.of(it))
            }
            mediaCol?.also {
                add(Members.mediaCol.of(it))
            }
        } + _extras)
    }

    /** Type for attributes of this collection */
    class Type(name: String): TypedCollectionType<InsertSheet>(Members, name)

    companion object Members : CollectionParser<InsertSheet> {
        override val typeName = InsertSheet::class.java.simpleName!!
        override fun fromAttributes(attributes: List<Attribute<*>>): InsertSheet {
            val remain = attributes.toMutableList()
            return InsertSheet(
                extractOne(remain, insertAfterPageNumber),
                extractOne(remain, insertCount),
                extractOne(remain, media),
                extractOne(remain, mediaCol),
                _extras = remain)
        }
        /** "insert-after-page-number" member type */
        @JvmField val insertAfterPageNumber = IntegerType("insert-after-page-number")
        /** "insert-count" member type */
        @JvmField val insertCount = IntegerType("insert-count")
        /** "media" member type */
        @JvmField val media = Media.Type("media")
        /** "media-col" member type */
        @JvmField val mediaCol = MediaCol.Type("media-col")
    }

    /**
     * All allowed member names in keyword form.
     */
    data class Keywords(
        override val value: String
    ) : Keyword() {
        override fun toString() = value
        /** An attribute type for [InsertSheet] member names as keywords */
        class Type(name: String) : KeywordType<Keywords>(Encoder, name)

        companion object {
            /** "insert-after-page-number" member type */
            @JvmField val insertAfterPageNumber = Keywords(Members.insertAfterPageNumber.name)
            /** "insert-count" member type */
            @JvmField val insertCount = Keywords(Members.insertCount.name)
            /** "media" member type */
            @JvmField val media = Keywords(Members.media.name)
            /** "media-col" member type */
            @JvmField val mediaCol = Keywords(Members.mediaCol.name)

            @JvmField val Encoder = KeywordType.encoderOf(Keywords::class.java) { value, _, _ ->
                Keywords(value)
            }
        }
    }
}
