// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "ipp-features-supported" keyword as defined in:
 *   * [APPLE-ICC](http://www.pwg.org/pipermail/ipp/2016/018914.html)
 *   * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
 *   * [PWG5100.14](http://ftp.pwg.org/pub/pwg/candidates/cs-ippeve10-20130128-5100.14.pdf)
 *   * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
 *   * [PWG5100.17](http://ftp.pwg.org/pub/pwg/candidates/cs-ippscan10-20140918-5100.17.pdf)
 *   * [PWG5100.18](http://ftp.pwg.org/pub/pwg/candidates/cs-ippinfra10-20150619-5100.18.pdf)
 *   * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
 */
data class IppFeature(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [IppFeature] attributes */
    class Type(name: String) : KeywordType<IppFeature>(Encoder, name)

    companion object {
        @JvmField val documentObject = IppFeature("document-object")
        @JvmField val faxout = IppFeature("faxout")
        @JvmField val iccColorMatching = IppFeature("icc-color-matching")
        @JvmField val infrastructurePrinter = IppFeature("infrastructure-printer")
        @JvmField val ipp3D = IppFeature("ipp-3d")
        @JvmField val ippEverywhere = IppFeature("ipp-everywhere")
        @JvmField val jobSave = IppFeature("job-save")
        @JvmField val none = IppFeature("none")
        @JvmField val pageOverrides = IppFeature("page-overrides")
        @JvmField val proofPrint = IppFeature("proof-print")
        @JvmField val scan = IppFeature("scan")
        @JvmField val subscriptionObject = IppFeature("subscription-object")
        @JvmField val Encoder = KeywordType.encoderOf(IppFeature::class.java) { value, _, _ ->
            IppFeature(value)
        }
    }
}
