// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.KeywordOrName
import com.hp.jipp.encoding.KeywordType
import com.hp.jipp.encoding.Tag

/**
 * "job-account-type" keyword as defined in:
 *   * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
 *
 * Also used by:
 *   * `job-account-type-default`
 *   * `job-account-type-supported`
 */
data class JobAccountType(
    override val value: String,
    override val tag: Tag = Tag.keyword,
    override val language: String? = null
) : KeywordOrName() {

    constructor(value: String): this(value, Tag.keyword)

    override fun toString() = value

    /** An attribute type for [JobAccountType] attributes */
    class Type(name: String) : KeywordType<JobAccountType>(Encoder, name)

    companion object {
        @JvmField val general = JobAccountType("general")
        @JvmField val group = JobAccountType("group")
        @JvmField val none = JobAccountType("none")
        @JvmField val Encoder = KeywordType.encoderOf(JobAccountType::class.java) { value, tag, language ->
            JobAccountType(value, tag, language)
        }
    }
}
