// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "job-error-sheet-when" keyword as defined in
 * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf).
 */
data class JobErrorSheetWhen(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [JobErrorSheetWhen] attributes */
    class Type(name: String) : KeywordType<JobErrorSheetWhen>(Encoder, name)

    companion object {
        @JvmField val always = JobErrorSheetWhen("always")
        @JvmField val onError = JobErrorSheetWhen("on-error")
        @JvmField val Encoder = KeywordType.encoderOf(JobErrorSheetWhen::class.java) { value, _, _ ->
            JobErrorSheetWhen(value)
        }
    }
}
