// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.KeywordOrName
import com.hp.jipp.encoding.KeywordType
import com.hp.jipp.encoding.Tag

/**
 * "job-password-repertoire-supported" keyword as defined in:
 *   * [IPPWG20160229-1](http://ftp.pwg.org/pub/pwg/ipp/wd/wp-job-password-repertoire-20160101.pdf)
 *
 * Also used by:
 *   * `job-password-repertoire-configured`
 */
data class JobPasswordRepertoireSupported(
    override val value: String,
    override val tag: Tag = Tag.keyword,
    override val language: String? = null
) : KeywordOrName() {

    constructor(value: String): this(value, Tag.keyword)

    override fun toString() = value

    /** An attribute type for [JobPasswordRepertoireSupported] attributes */
    class Type(name: String) : KeywordType<JobPasswordRepertoireSupported>(Encoder, name)

    companion object {
        @JvmField val ianaUsAsciiAny = JobPasswordRepertoireSupported("iana_us-ascii_any")
        @JvmField val ianaUsAsciiComplex = JobPasswordRepertoireSupported("iana_us-ascii_complex")
        @JvmField val ianaUsAsciiDigits = JobPasswordRepertoireSupported("iana_us-ascii_digits")
        @JvmField val ianaUsAsciiLetters = JobPasswordRepertoireSupported("iana_us-ascii_letters")
        @JvmField val ianaUtf8Any = JobPasswordRepertoireSupported("iana_utf-8_any")
        @JvmField val ianaUtf8Digits = JobPasswordRepertoireSupported("iana_utf-8_digits")
        @JvmField val ianaUtf8Letters = JobPasswordRepertoireSupported("iana_utf-8_letters")
        @JvmField val Encoder = KeywordType.encoderOf(JobPasswordRepertoireSupported::class.java) { value, tag, language ->
            JobPasswordRepertoireSupported(value, tag, language)
        }
    }
}
