// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "job-presets-supported" collection as defined in:
 * [IPPPRESET](https://ftp.pwg.org/pub/pwg/ipp/registrations/reg-ipppreset-20171214.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class JobPresetsSupported
@JvmOverloads constructor(
    val presetName: PresetName? = null,
    val _extras: List<Attribute<*>> = listOf()
) : HasAttributeCollection {

    /** Generate attribute list */
    override val attributes: AttributeCollection by lazy {
        AttributeCollection(mutableListOf<Attribute<*>>().apply {
            presetName?.also {
                add(Members.presetName.of(it))
            }
        } + _extras)
    }

    /** Type for attributes of this collection */
    class Type(name: String): TypedCollectionType<JobPresetsSupported>(Members, name)

    companion object Members : CollectionParser<JobPresetsSupported> {
        override val typeName = JobPresetsSupported::class.java.simpleName!!
        override fun fromAttributes(attributes: List<Attribute<*>>): JobPresetsSupported {
            val remain = attributes.toMutableList()
            return JobPresetsSupported(
                extractOne(remain, presetName),
                _extras = remain)
        }
        /** "preset-name" member type */
        @JvmField val presetName = PresetName.Type("preset-name")
    }

    /**
     * All allowed member names in keyword form.
     */
    data class Keywords(
        override val value: String
    ) : Keyword() {
        override fun toString() = value
        /** An attribute type for [JobPresetsSupported] member names as keywords */
        class Type(name: String) : KeywordType<Keywords>(Encoder, name)

        companion object {
            /** "preset-name" member type */
            @JvmField val presetName = Keywords(Members.presetName.name)

            @JvmField val Encoder = KeywordType.encoderOf(Keywords::class.java) { value, _, _ ->
                Keywords(value)
            }
        }
    }
}
