// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "job-save-disposition-supported" keyword as defined in
 * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf).
 */
data class JobSaveDispositionSupported(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [JobSaveDispositionSupported] attributes */
    class Type(name: String) : KeywordType<JobSaveDispositionSupported>(Encoder, name)

    companion object {
        @JvmField val saveDisposition = JobSaveDispositionSupported("save-disposition")
        @JvmField val saveInfo = JobSaveDispositionSupported("save-info")
        @JvmField val Encoder = KeywordType.encoderOf(JobSaveDispositionSupported::class.java) { value, _, _ ->
            JobSaveDispositionSupported(value)
        }
    }
}
