// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "job-spooling-supported" keyword as defined in:
 *   * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
 */
data class JobSpoolingSupported(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [JobSpoolingSupported] attributes */
    class Type(name: String) : KeywordType<JobSpoolingSupported>(Encoder, name)

    companion object {
        @JvmField val automatic = JobSpoolingSupported("automatic")
        @JvmField val spool = JobSpoolingSupported("spool")
        @JvmField val stream = JobSpoolingSupported("stream")
        @JvmField val Encoder = KeywordType.encoderOf(JobSpoolingSupported::class.java) { value, _, _ ->
            JobSpoolingSupported(value)
        }
    }
}
