// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "laminating-sides" keyword as defined in:
 *   * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
 *
 * Also used by:
 *   * `laminating-sides-supported`
 */
data class LaminatingSides(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [LaminatingSides] attributes */
    class Type(name: String) : KeywordType<LaminatingSides>(Encoder, name)

    companion object {
        @JvmField val back = LaminatingSides("back")
        @JvmField val both = LaminatingSides("both")
        @JvmField val front = LaminatingSides("front")
        @JvmField val Encoder = KeywordType.encoderOf(LaminatingSides::class.java) { value, _, _ ->
            LaminatingSides(value)
        }
    }
}
