// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "materials-col-supported" keyword as defined in:
 *   * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
 */
data class MaterialsCol(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [MaterialsCol] attributes */
    class Type(name: String) : KeywordType<MaterialsCol>(Encoder, name)

    companion object {
        @JvmField val materialAmount = MaterialsCol("material-amount")
        @JvmField val materialAmountUnits = MaterialsCol("material-amount-units")
        @JvmField val materialColor = MaterialsCol("material-color")
        @JvmField val materialDiameter = MaterialsCol("material-diameter")
        @JvmField val materialDiameterTolerance = MaterialsCol("material-diameter-tolerance")
        @JvmField val materialFillDensity = MaterialsCol("material-fill-density")
        @JvmField val materialKey = MaterialsCol("material-key")
        @JvmField val materialName = MaterialsCol("material-name")
        @JvmField val materialPurpose = MaterialsCol("material-purpose")
        @JvmField val materialRate = MaterialsCol("material-rate")
        @JvmField val materialRateUnits = MaterialsCol("material-rate-units")
        @JvmField val materialShellThickness = MaterialsCol("material-shell-thickness")
        @JvmField val materialTemperature = MaterialsCol("material-temperature")
        @JvmField val materialType = MaterialsCol("material-type")
        @JvmField val Encoder = KeywordType.encoderOf(MaterialsCol::class.java) { value, _, _ ->
            MaterialsCol(value)
        }
    }
}
