// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "media-col-supported" keyword as defined in:
 *   * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
 */
data class MediaCol(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [MediaCol] attributes */
    class Type(name: String) : KeywordType<MediaCol>(Encoder, name)

    companion object {
        @JvmField val mediaBottomMargin = MediaCol("media-bottom-margin")
        @JvmField val mediaLeftMargin = MediaCol("media-left-margin")
        @JvmField val mediaRightMargin = MediaCol("media-right-margin")
        @JvmField val mediaSizeName = MediaCol("media-size-name")
        @JvmField val mediaSource = MediaCol("media-source")
        @JvmField val mediaTopMargin = MediaCol("media-top-margin")
        @JvmField val Encoder = KeywordType.encoderOf(MediaCol::class.java) { value, _, _ ->
            MediaCol(value)
        }
    }
}
