// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "media-col-supported" keyword as defined in
 * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf).
 */
data class MediaColSupported(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [MediaColSupported] attributes */
    class Type(name: String) : KeywordType<MediaColSupported>(Encoder, name)

    companion object {
        @JvmField val mediaBottomMargin = MediaColSupported("media-bottom-margin")
        @JvmField val mediaLeftMargin = MediaColSupported("media-left-margin")
        @JvmField val mediaRightMargin = MediaColSupported("media-right-margin")
        @JvmField val mediaSizeName = MediaColSupported("media-size-name")
        @JvmField val mediaSource = MediaColSupported("media-source")
        @JvmField val mediaTopMargin = MediaColSupported("media-top-margin")
        @JvmField val Encoder = KeywordType.encoderOf(MediaColSupported::class.java) { value, _, _ ->
            MediaColSupported(value)
        }
    }
}
