// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.KeywordOrName
import com.hp.jipp.encoding.KeywordType
import com.hp.jipp.encoding.Tag

/**
 * "media-grain" keyword as defined in
 * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf).
 *
 * Also used by:
 *   * `media-grain-supported`
 */
data class MediaGrain(
    override val value: String,
    override val tag: Tag = Tag.keyword,
    override val language: String? = null
) : KeywordOrName() {

    /** Construct a [Tag.keyword] form of this preset */
    constructor(value: String): this(value, Tag.keyword)

    override fun toString() = value

    /** An attribute type for [MediaGrain] attributes */
    class Type(name: String) : KeywordType<MediaGrain>(Encoder, name)

    companion object {
        @JvmField val xDirection = MediaGrain("x-direction")
        @JvmField val yDirection = MediaGrain("y-direction")
        @JvmField val Encoder = KeywordType.encoderOf(MediaGrain::class.java) { value, tag, language ->
            MediaGrain(value, tag, language)
        }
    }
}
