// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.KeywordOrName
import com.hp.jipp.encoding.KeywordType
import com.hp.jipp.encoding.Tag

/**
 * "media-color" keyword as defined in:
 *   * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
 *   * [PWG5101.1](http://ftp.pwg.org/pub/pwg/candidates/cs-pwgmsn10-20020226-5101.1.pdf)
 *
 * Also used by:
 *   * `material-color`
 *   * `media-color-supported`
 */
data class MediaColor(
    override val value: String,
    override val tag: Tag = Tag.keyword,
    override val language: String? = null
) : KeywordOrName() {

    constructor(value: String): this(value, Tag.keyword)

    override fun toString() = value

    /** An attribute type for [MediaColor] attributes */
    class Type(name: String) : KeywordType<MediaColor>(Encoder, name)

    companion object {
        @JvmField val black = MediaColor("black")
        @JvmField val blue = MediaColor("blue")
        @JvmField val brown = MediaColor("brown")
        @JvmField val buff = MediaColor("buff")
        @JvmField val clearBlack = MediaColor("clear-black")
        @JvmField val clearBlue = MediaColor("clear-blue")
        @JvmField val clearBrown = MediaColor("clear-brown")
        @JvmField val clearBuff = MediaColor("clear-buff")
        @JvmField val clearCyan = MediaColor("clear-cyan")
        @JvmField val clearGold = MediaColor("clear-gold")
        @JvmField val clearGoldenrod = MediaColor("clear-goldenrod")
        @JvmField val clearGray = MediaColor("clear-gray")
        @JvmField val clearGreen = MediaColor("clear-green")
        @JvmField val clearIvory = MediaColor("clear-ivory")
        @JvmField val clearMagenta = MediaColor("clear-magenta")
        @JvmField val clearMultiColor = MediaColor("clear-multi-color")
        @JvmField val clearMustard = MediaColor("clear-mustard")
        @JvmField val clearOrange = MediaColor("clear-orange")
        @JvmField val clearPink = MediaColor("clear-pink")
        @JvmField val clearRed = MediaColor("clear-red")
        @JvmField val clearSilver = MediaColor("clear-silver")
        @JvmField val clearTurquoise = MediaColor("clear-turquoise")
        @JvmField val clearViolet = MediaColor("clear-violet")
        @JvmField val clearWhite = MediaColor("clear-white")
        @JvmField val clearYellow = MediaColor("clear-yellow")
        @JvmField val cyan = MediaColor("cyan")
        @JvmField val darkBlue = MediaColor("dark-blue")
        @JvmField val darkBrown = MediaColor("dark-brown")
        @JvmField val darkBuff = MediaColor("dark-buff")
        @JvmField val darkCyan = MediaColor("dark-cyan")
        @JvmField val darkGold = MediaColor("dark-gold")
        @JvmField val darkGoldenrod = MediaColor("dark-goldenrod")
        @JvmField val darkGray = MediaColor("dark-gray")
        @JvmField val darkGreen = MediaColor("dark-green")
        @JvmField val darkIvory = MediaColor("dark-ivory")
        @JvmField val darkMagenta = MediaColor("dark-magenta")
        @JvmField val darkMustard = MediaColor("dark-mustard")
        @JvmField val darkOrange = MediaColor("dark-orange")
        @JvmField val darkPink = MediaColor("dark-pink")
        @JvmField val darkRed = MediaColor("dark-red")
        @JvmField val darkSilver = MediaColor("dark-silver")
        @JvmField val darkTurquoise = MediaColor("dark-turquoise")
        @JvmField val darkViolet = MediaColor("dark-violet")
        @JvmField val darkYellow = MediaColor("dark-yellow")
        @JvmField val gold = MediaColor("gold")
        @JvmField val goldenrod = MediaColor("goldenrod")
        @JvmField val gray = MediaColor("gray")
        @JvmField val green = MediaColor("green")
        @JvmField val ivory = MediaColor("ivory")
        @JvmField val lightBlack = MediaColor("light-black")
        @JvmField val lightBlue = MediaColor("light-blue")
        @JvmField val lightBrown = MediaColor("light-brown")
        @JvmField val lightBuff = MediaColor("light-buff")
        @JvmField val lightCyan = MediaColor("light-cyan")
        @JvmField val lightGold = MediaColor("light-gold")
        @JvmField val lightGoldenrod = MediaColor("light-goldenrod")
        @JvmField val lightGray = MediaColor("light-gray")
        @JvmField val lightGreen = MediaColor("light-green")
        @JvmField val lightIvory = MediaColor("light-ivory")
        @JvmField val lightMagenta = MediaColor("light-magenta")
        @JvmField val lightMustard = MediaColor("light-mustard")
        @JvmField val lightOrange = MediaColor("light-orange")
        @JvmField val lightPink = MediaColor("light-pink")
        @JvmField val lightRed = MediaColor("light-red")
        @JvmField val lightSilver = MediaColor("light-silver")
        @JvmField val lightTurquoise = MediaColor("light-turquoise")
        @JvmField val lightViolet = MediaColor("light-violet")
        @JvmField val lightYellow = MediaColor("light-yellow")
        @JvmField val magenta = MediaColor("magenta")
        @JvmField val multiColor = MediaColor("multi-color")
        @JvmField val mustard = MediaColor("mustard")
        @JvmField val noColor = MediaColor("no-color")
        @JvmField val orange = MediaColor("orange")
        @JvmField val pink = MediaColor("pink")
        @JvmField val red = MediaColor("red")
        @JvmField val silver = MediaColor("silver")
        @JvmField val turquoise = MediaColor("turquoise")
        @JvmField val violet = MediaColor("violet")
        @JvmField val white = MediaColor("white")
        @JvmField val yellow = MediaColor("yellow")
        @JvmField val Encoder = KeywordType.encoderOf(MediaColor::class.java) { value, tag, language ->
            MediaColor(value, tag, language)
        }
    }
}
