// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.KeywordOrName
import com.hp.jipp.encoding.KeywordType
import com.hp.jipp.encoding.Tag

/**
 * "media-tooth" keyword as defined in:
 *   * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
 *
 * Also used by:
 *   * `media-tooth-supported`
 */
data class MediaTooth(
    override val value: String,
    override val tag: Tag = Tag.keyword,
    override val language: String? = null
) : KeywordOrName() {

    constructor(value: String): this(value, Tag.keyword)

    override fun toString() = value

    /** An attribute type for [MediaTooth] attributes */
    class Type(name: String) : KeywordType<MediaTooth>(Encoder, name)

    companion object {
        @JvmField val antique = MediaTooth("antique")
        @JvmField val calendared = MediaTooth("calendared")
        @JvmField val coarse = MediaTooth("coarse")
        @JvmField val fine = MediaTooth("fine")
        @JvmField val linen = MediaTooth("linen")
        @JvmField val medium = MediaTooth("medium")
        @JvmField val smooth = MediaTooth("smooth")
        @JvmField val stipple = MediaTooth("stipple")
        @JvmField val uncalendared = MediaTooth("uncalendared")
        @JvmField val vellum = MediaTooth("vellum")
        @JvmField val Encoder = KeywordType.encoderOf(MediaTooth::class.java) { value, tag, language ->
            MediaTooth(value, tag, language)
        }
    }
}
