// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "multiple-operation-time-out-action" keyword as defined in:
 *   * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
 */
data class MultipleOperationTimeOutAction(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [MultipleOperationTimeOutAction] attributes */
    class Type(name: String) : KeywordType<MultipleOperationTimeOutAction>(Encoder, name)

    companion object {
        @JvmField val abortJob = MultipleOperationTimeOutAction("abort-job")
        @JvmField val holdJob = MultipleOperationTimeOutAction("hold-job")
        @JvmField val processJob = MultipleOperationTimeOutAction("process-job")
        @JvmField val Encoder = KeywordType.encoderOf(MultipleOperationTimeOutAction::class.java) { value, _, _ ->
            MultipleOperationTimeOutAction(value)
        }
    }
}
