// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "notify-pull-method" keyword as defined in:
 *   * [RFC3995](http://www.iana.org/go/rfc3995)
 *   * [RFC3996](http://www.iana.org/go/rfc3996)
 *
 * Also used by:
 *   * `notify-pull-method-supported`
 */
data class NotifyPullMethod(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [NotifyPullMethod] attributes */
    class Type(name: String) : KeywordType<NotifyPullMethod>(Encoder, name)

    companion object {
        @JvmField val ippget = NotifyPullMethod("ippget")
        @JvmField val Encoder = KeywordType.encoderOf(NotifyPullMethod::class.java) { value, _, _ ->
            NotifyPullMethod(value)
        }
    }
}
