// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "notify-events" keyword as defined in:
 *   * [PWG5100.18](http://ftp.pwg.org/pub/pwg/candidates/cs-ippinfra10-20150619-5100.18.pdf)
 *   * [RFC3995](http://www.iana.org/go/rfc3995)
 *
 * Also used by:
 *   * `notify-events-default`
 *   * `notify-events-supported`
 *   * `notify-subscribed-event`
 */
data class NotifyEvent(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [NotifyEvent] attributes */
    class Type(name: String) : KeywordType<NotifyEvent>(Encoder, name)

    companion object {
        @JvmField val documentCompleted = NotifyEvent("document-completed")
        @JvmField val documentConfigChanged = NotifyEvent("document-config-changed")
        @JvmField val documentCreated = NotifyEvent("document-created")
        @JvmField val documentFetchable = NotifyEvent("document-fetchable")
        @JvmField val documentStateChanged = NotifyEvent("document-state-changed")
        @JvmField val documentStopped = NotifyEvent("document-stopped")
        @JvmField val jobCompleted = NotifyEvent("job-completed")
        @JvmField val jobConfigChanged = NotifyEvent("job-config-changed")
        @JvmField val jobCreated = NotifyEvent("job-created")
        @JvmField val jobFetchable = NotifyEvent("job-fetchable")
        @JvmField val jobProgress = NotifyEvent("job-progress")
        @JvmField val jobStateChanged = NotifyEvent("job-state-changed")
        @JvmField val jobStopped = NotifyEvent("job-stopped")
        @JvmField val none = NotifyEvent("none")
        @JvmField val printerConfigChanged = NotifyEvent("printer-config-changed")
        @JvmField val printerFinishingsChanged = NotifyEvent("printer-finishings-changed")
        @JvmField val printerMediaChanged = NotifyEvent("printer-media-changed")
        @JvmField val printerQueueOrderChanged = NotifyEvent("printer-queue-order-changed")
        @JvmField val printerRestarted = NotifyEvent("printer-restarted")
        @JvmField val printerShutdown = NotifyEvent("printer-shutdown")
        @JvmField val printerStateChanged = NotifyEvent("printer-state-changed")
        @JvmField val printerStopped = NotifyEvent("printer-stopped")
        @JvmField val Encoder = KeywordType.encoderOf(NotifyEvent::class.java) { value, _, _ ->
            NotifyEvent(value)
        }
    }
}
