// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "output-attributes" collection as defined in:
 *   * [PWG5100.17](http://ftp.pwg.org/pub/pwg/candidates/cs-ippscan10-20140918-5100.17.pdf)
 */
data class OutputAttributes
@JvmOverloads constructor(
    val noiseRemoval: Int? = null,
    val outputCompressionQualityFactor: Int? = null,
    val _extras: List<Attribute<*>> = listOf()
) : HasAttributeCollection {

    /** Generate attribute list */
    override val attributes: AttributeCollection by lazy {
        AttributeCollection(mutableListOf<Attribute<*>>().apply {
            noiseRemoval?.also {
                add(Members.noiseRemoval.of(it))
            }
            outputCompressionQualityFactor?.also {
                add(Members.outputCompressionQualityFactor.of(it))
            }
        } + _extras)
    }

    /** Type for attributes of this collection */
    class Type(name: String): TypedCollectionType<OutputAttributes>(Members, name)

    companion object Members : CollectionParser<OutputAttributes> {
        override val typeName = OutputAttributes::class.java.simpleName!!
        override fun fromAttributes(attributes: List<Attribute<*>>): OutputAttributes {
            val remain = attributes.toMutableList()
            return OutputAttributes(
                extractOne(remain, noiseRemoval),
                extractOne(remain, outputCompressionQualityFactor),
                _extras = remain)
        }
        /** "noise-removal" member type */
        @JvmField val noiseRemoval = IntegerType("noise-removal")
        /** "output-compression-quality-factor" member type */
        @JvmField val outputCompressionQualityFactor = IntegerType("output-compression-quality-factor")
    }

    /**
     * All allowed member names in keyword form.
     */
    data class Keywords(
        override val value: String
    ) : Keyword() {
        override fun toString() = value
        /** An attribute type for [OutputAttributes] member names as keywords */
        class Type(name: String) : KeywordType<Keywords>(Encoder, name)

        companion object {
            /** "noise-removal" member type */
            @JvmField val noiseRemoval = Keywords(Members.noiseRemoval.name)
            /** "output-compression-quality-factor" member type */
            @JvmField val outputCompressionQualityFactor = Keywords(Members.outputCompressionQualityFactor.name)

            @JvmField val Encoder = KeywordType.encoderOf(Keywords::class.java) { value, _, _ ->
                Keywords(value)
            }
        }
    }
}