// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "pdf-versions-supported" keyword as defined in:
 *   * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
 */
data class PdfVersions(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [PdfVersions] attributes */
    class Type(name: String) : KeywordType<PdfVersions>(Encoder, name)

    companion object {
        @JvmField val adobe13 = PdfVersions("adobe-1.3")
        @JvmField val adobe14 = PdfVersions("adobe-1.4")
        @JvmField val adobe15 = PdfVersions("adobe-1.5")
        @JvmField val adobe16 = PdfVersions("adobe-1.6")
        @JvmField val iso1593012001 = PdfVersions("iso-15930-1_2001")
        @JvmField val iso1593032002 = PdfVersions("iso-15930-3_2002")
        @JvmField val iso1593042003 = PdfVersions("iso-15930-4_2003")
        @JvmField val iso1593062003 = PdfVersions("iso-15930-6_2003")
        @JvmField val iso1593072010 = PdfVersions("iso-15930-7_2010")
        @JvmField val iso1593082010 = PdfVersions("iso-15930-8_2010")
        @JvmField val iso1661222010 = PdfVersions("iso-16612-2_2010")
        @JvmField val iso1900512005 = PdfVersions("iso-19005-1_2005")
        @JvmField val iso1900522011 = PdfVersions("iso-19005-2_2011")
        @JvmField val iso1900532012 = PdfVersions("iso-19005-3_2012")
        @JvmField val iso3200012008 = PdfVersions("iso-32000-1_2008")
        @JvmField val none = PdfVersions("none")
        @JvmField val pwg51023 = PdfVersions("pwg-5102.3")
        @JvmField val Encoder = KeywordType.encoderOf(PdfVersions::class.java) { value, _, _ ->
            PdfVersions(value)
        }
    }
}
