// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "pdl-init-file" collection as defined in:
 * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class PdlInitFile
@JvmOverloads constructor(
    val pdlInitFileEntry: String? = null,
    val pdlInitFileLocation: java.net.URI? = null,
    val pdlInitFileName: String? = null,
    val _extras: List<Attribute<*>> = listOf()
) : HasAttributeCollection {

    /** Generate attribute list */
    override val attributes: AttributeCollection by lazy {
        AttributeCollection(mutableListOf<Attribute<*>>().apply {
            pdlInitFileEntry?.also {
                add(Members.pdlInitFileEntry.of(it))
            }
            pdlInitFileLocation?.also {
                add(Members.pdlInitFileLocation.of(it))
            }
            pdlInitFileName?.also {
                add(Members.pdlInitFileName.of(it))
            }
        } + _extras)
    }

    /** Type for attributes of this collection */
    class Type(name: String): TypedCollectionType<PdlInitFile>(Members, name)

    companion object Members : CollectionParser<PdlInitFile> {
        override val typeName = PdlInitFile::class.java.simpleName!!
        override fun fromAttributes(attributes: List<Attribute<*>>): PdlInitFile {
            val remain = attributes.toMutableList()
            return PdlInitFile(
                extractOne(remain, pdlInitFileEntry)?.value,
                extractOne(remain, pdlInitFileLocation),
                extractOne(remain, pdlInitFileName)?.value,
                _extras = remain)
        }
        /** "pdl-init-file-entry" member type */
        @JvmField val pdlInitFileEntry = NameType("pdl-init-file-entry")
        /** "pdl-init-file-location" member type */
        @JvmField val pdlInitFileLocation = UriType("pdl-init-file-location")
        /** "pdl-init-file-name" member type */
        @JvmField val pdlInitFileName = NameType("pdl-init-file-name")
    }

    /**
     * All allowed member names in keyword form.
     */
    data class Keywords(
        override val value: String
    ) : Keyword() {
        override fun toString() = value
        /** An attribute type for [PdlInitFile] member names as keywords */
        class Type(name: String) : KeywordType<Keywords>(Encoder, name)

        companion object {
            /** "pdl-init-file-entry" member type */
            @JvmField val pdlInitFileEntry = Keywords(Members.pdlInitFileEntry.name)
            /** "pdl-init-file-location" member type */
            @JvmField val pdlInitFileLocation = Keywords(Members.pdlInitFileLocation.name)
            /** "pdl-init-file-name" member type */
            @JvmField val pdlInitFileName = Keywords(Members.pdlInitFileName.name)

            @JvmField val Encoder = KeywordType.encoderOf(Keywords::class.java) { value, _, _ ->
                Keywords(value)
            }
        }
    }
}
