// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "pdl-override-supported" keyword as defined in:
 *   * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
 *   * [RFC8011](http://www.iana.org/go/rfc8011)
 */
data class PdlOverrideSupported(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [PdlOverrideSupported] attributes */
    class Type(name: String) : KeywordType<PdlOverrideSupported>(Encoder, name)

    companion object {
        @JvmField val attempted = PdlOverrideSupported("attempted")
        @JvmField val guaranteed = PdlOverrideSupported("guaranteed")
        @JvmField val notAttempted = PdlOverrideSupported("not-attempted")
        @JvmField val Encoder = KeywordType.encoderOf(PdlOverrideSupported::class.java) { value, _, _ ->
            PdlOverrideSupported(value)
        }
    }
}
