// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "pdl-override-guaranteed-supported" keyword as defined in:
 *   * [IPPWG20151019](http://www.pwg.org/archives/ipp/2015/018629.html)
 */
data class PdlOverrideGuaranteedSupported(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [PdlOverrideGuaranteedSupported] attributes */
    class Type(name: String) : KeywordType<PdlOverrideGuaranteedSupported>(Encoder, name)

    companion object {
        @JvmField val confirmationSheetPrint = PdlOverrideGuaranteedSupported("confirmation-sheet-print")
        @JvmField val copies = PdlOverrideGuaranteedSupported("copies")
        @JvmField val coverBack = PdlOverrideGuaranteedSupported("cover-back")
        @JvmField val coverFront = PdlOverrideGuaranteedSupported("cover-front")
        @JvmField val coverSheetInfo = PdlOverrideGuaranteedSupported("cover-sheet-info")
        @JvmField val destinationStatuses = PdlOverrideGuaranteedSupported("destination-statuses")
        @JvmField val destinationUris = PdlOverrideGuaranteedSupported("destination-uris")
        @JvmField val feedOrientation = PdlOverrideGuaranteedSupported("feed-orientation")
        @JvmField val finishings = PdlOverrideGuaranteedSupported("finishings")
        @JvmField val finishingsCol = PdlOverrideGuaranteedSupported("finishings-col")
        @JvmField val fontNameRequested = PdlOverrideGuaranteedSupported("font-name-requested")
        @JvmField val fontSizeRequested = PdlOverrideGuaranteedSupported("font-size-requested")
        @JvmField val forceFrontSide = PdlOverrideGuaranteedSupported("force-front-side")
        @JvmField val impositionTemplate = PdlOverrideGuaranteedSupported("imposition-template")
        @JvmField val insertSheet = PdlOverrideGuaranteedSupported("insert-sheet")
        @JvmField val jobAccountId = PdlOverrideGuaranteedSupported("job-account-id")
        @JvmField val jobAccountType = PdlOverrideGuaranteedSupported("job-account-type")
        @JvmField val jobAccountingSheets = PdlOverrideGuaranteedSupported("job-accounting-sheets")
        @JvmField val jobAccountingUserId = PdlOverrideGuaranteedSupported("job-accounting-user-id")
        @JvmField val jobCopies = PdlOverrideGuaranteedSupported("job-copies")
        @JvmField val jobCoverBack = PdlOverrideGuaranteedSupported("job-cover-back")
        @JvmField val jobCoverFront = PdlOverrideGuaranteedSupported("job-cover-front")
        @JvmField val jobDelayOutputUntil = PdlOverrideGuaranteedSupported("job-delay-output-until")
        @JvmField val jobDelayOutputUntilTime = PdlOverrideGuaranteedSupported("job-delay-output-until-time")
        @JvmField val jobErrorAction = PdlOverrideGuaranteedSupported("job-error-action")
        @JvmField val jobErrorSheet = PdlOverrideGuaranteedSupported("job-error-sheet")
        @JvmField val jobFinishings = PdlOverrideGuaranteedSupported("job-finishings")
        @JvmField val jobFinishingsCol = PdlOverrideGuaranteedSupported("job-finishings-col")
        @JvmField val jobHoldUntil = PdlOverrideGuaranteedSupported("job-hold-until")
        @JvmField val jobHoldUntilTime = PdlOverrideGuaranteedSupported("job-hold-until-time")
        @JvmField val jobMessageToOperator = PdlOverrideGuaranteedSupported("job-message-to-operator")
        @JvmField val jobPagesPerSet = PdlOverrideGuaranteedSupported("job-pages-per-set")
        @JvmField val jobPhoneNumber = PdlOverrideGuaranteedSupported("job-phone-number")
        @JvmField val jobPriority = PdlOverrideGuaranteedSupported("job-priority")
        @JvmField val jobRecipientName = PdlOverrideGuaranteedSupported("job-recipient-name")
        @JvmField val jobSaveDisposition = PdlOverrideGuaranteedSupported("job-save-disposition")
        @JvmField val jobSheetMessage = PdlOverrideGuaranteedSupported("job-sheet-message")
        @JvmField val jobSheets = PdlOverrideGuaranteedSupported("job-sheets")
        @JvmField val jobSheetsCol = PdlOverrideGuaranteedSupported("job-sheets-col")
        @JvmField val materialsCol = PdlOverrideGuaranteedSupported("materials-col")
        @JvmField val media = PdlOverrideGuaranteedSupported("media")
        @JvmField val mediaCol = PdlOverrideGuaranteedSupported("media-col")
        @JvmField val mediaInputTrayCheck = PdlOverrideGuaranteedSupported("media-input-tray-check")
        @JvmField val multipleDocumentHandling = PdlOverrideGuaranteedSupported("multiple-document-handling")
        @JvmField val multipleObjectHandling = PdlOverrideGuaranteedSupported("multiple-object-handling")
        @JvmField val numberOfRetries = PdlOverrideGuaranteedSupported("number-of-retries")
        @JvmField val numberUp = PdlOverrideGuaranteedSupported("number-up")
        @JvmField val orientationRequested = PdlOverrideGuaranteedSupported("orientation-requested")
        @JvmField val outputBin = PdlOverrideGuaranteedSupported("output-bin")
        @JvmField val outputDevice = PdlOverrideGuaranteedSupported("output-device")
        @JvmField val overrides = PdlOverrideGuaranteedSupported("overrides")
        @JvmField val pageDelivery = PdlOverrideGuaranteedSupported("page-delivery")
        @JvmField val pageOrderReceived = PdlOverrideGuaranteedSupported("page-order-received")
        @JvmField val pageRanges = PdlOverrideGuaranteedSupported("page-ranges")
        @JvmField val pagesPerSubset = PdlOverrideGuaranteedSupported("pages-per-subset")
        @JvmField val pdlInitFile = PdlOverrideGuaranteedSupported("pdl-init-file")
        @JvmField val platformTemperature = PdlOverrideGuaranteedSupported("platform-temperature")
        @JvmField val presentationDirectionNumberUp = PdlOverrideGuaranteedSupported("presentation-direction-number-up")
        @JvmField val printAccuracy = PdlOverrideGuaranteedSupported("print-accuracy")
        @JvmField val printBase = PdlOverrideGuaranteedSupported("print-base")
        @JvmField val printColorMode = PdlOverrideGuaranteedSupported("print-color-mode")
        @JvmField val printContentOptimize = PdlOverrideGuaranteedSupported("print-content-optimize")
        @JvmField val printObjects = PdlOverrideGuaranteedSupported("print-objects")
        @JvmField val printQuality = PdlOverrideGuaranteedSupported("print-quality")
        @JvmField val printRenderingIntent = PdlOverrideGuaranteedSupported("print-rendering-intent")
        @JvmField val printScaling = PdlOverrideGuaranteedSupported("print-scaling")
        @JvmField val printSupports = PdlOverrideGuaranteedSupported("print-supports")
        @JvmField val printerResolution = PdlOverrideGuaranteedSupported("printer-resolution")
        @JvmField val proofPrint = PdlOverrideGuaranteedSupported("proof-print")
        @JvmField val retryInterval = PdlOverrideGuaranteedSupported("retry-interval")
        @JvmField val retryTimeOut = PdlOverrideGuaranteedSupported("retry-time-out")
        @JvmField val separatorSheets = PdlOverrideGuaranteedSupported("separator-sheets")
        @JvmField val sheetCollate = PdlOverrideGuaranteedSupported("sheet-collate")
        @JvmField val sides = PdlOverrideGuaranteedSupported("sides")
        @JvmField val xImagePosition = PdlOverrideGuaranteedSupported("x-image-position")
        @JvmField val xImageShift = PdlOverrideGuaranteedSupported("x-image-shift")
        @JvmField val xSide1ImageShift = PdlOverrideGuaranteedSupported("x-side1-image-shift")
        @JvmField val xSide2ImageShift = PdlOverrideGuaranteedSupported("x-side2-image-shift")
        @JvmField val yImagePosition = PdlOverrideGuaranteedSupported("y-image-position")
        @JvmField val yImageShift = PdlOverrideGuaranteedSupported("y-image-shift")
        @JvmField val ySide1ImageShift = PdlOverrideGuaranteedSupported("y-side1-image-shift")
        @JvmField val ySide2ImageShift = PdlOverrideGuaranteedSupported("y-side2-image-shift")
        @JvmField val Encoder = KeywordType.encoderOf(PdlOverrideGuaranteedSupported::class.java) { value, _, _ ->
            PdlOverrideGuaranteedSupported(value)
        }
    }
}
