// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports
import com.hp.jipp.util.getStaticObjects

/**
 * Printer Description attribute types.
 */
object PrinterDescription {

    /**
     * "accuracy-units-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val accuracyUnitsSupported = AccuracyUnits.Type("accuracy-units-supported")

    /**
     * "baling-type-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val balingTypeSupported = BalingType.Type("baling-type-supported")

    /**
     * "baling-when-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val balingWhenSupported = BalingWhen.Type("baling-when-supported")

    /**
     * "binding-reference-edge-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val bindingReferenceEdgeSupported = BindingReferenceEdge.Type("binding-reference-edge-supported")

    /**
     * "binding-type-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val bindingTypeSupported = BindingType.Type("binding-type-supported")

    /**
     * "charset-configured" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val charsetConfigured = StringType(Tag.charset, "charset-configured")

    /**
     * "charset-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val charsetSupported = StringType(Tag.charset, "charset-supported")

    /**
     * "coating-sides-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val coatingSidesSupported = CoatingSides.Type("coating-sides-supported")

    /**
     * "coating-type-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val coatingTypeSupported = CoatingType.Type("coating-type-supported")

    /**
     * "color-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val colorSupported = BooleanType("color-supported")

    /**
     * "compression-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val compressionSupported = Compression.Type("compression-supported")

    /**
     * "confirmation-sheet-print-default" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val confirmationSheetPrintDefault = BooleanType("confirmation-sheet-print-default")

    /**
     * "copies-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val copiesDefault = IntegerType("copies-default")

    /**
     * "copies-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val copiesSupported = RangeOfIntegerType("copies-supported")

    /**
     * "cover-back-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val coverBackSupported = CoverBack.Type("cover-back-supported")

    /**
     * "cover-front-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val coverFrontSupported = CoverBack.Type("cover-front-supported")

    /**
     * "cover-sheet-info-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val coverSheetInfoSupported = CoverSheetInfo.Type("cover-sheet-info-supported")

    /**
     * "covering-name-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val coveringNameSupported = CoveringName.Type("covering-name-supported")

    /**
     * "destination-uri-schemes-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val destinationUriSchemesSupported = UriType("destination-uri-schemes-supported")

    /**
     * "document-charset-default" as defined in:
     * [PWG5100.7](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext10-20031031-5100.7.pdf)
     */
    @JvmField val documentCharsetDefault = StringType(Tag.charset, "document-charset-default")

    /**
     * "document-charset-supported" as defined in:
     * [PWG5100.7](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext10-20031031-5100.7.pdf)
     */
    @JvmField val documentCharsetSupported = StringType(Tag.charset, "document-charset-supported")

    /**
     * "document-digital-signature-default" as defined in:
     * [PWG5100.7](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext10-20031031-5100.7.pdf)
     */
    @JvmField val documentDigitalSignatureDefault = DocumentDigitalSignature.Type("document-digital-signature-default")

    /**
     * "document-digital-signature-supported" as defined in:
     * [PWG5100.7](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext10-20031031-5100.7.pdf)
     */
    @JvmField val documentDigitalSignatureSupported = DocumentDigitalSignature.Type("document-digital-signature-supported")

    /**
     * "document-format-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val documentFormatDefault = StringType(Tag.mimeMediaType, "document-format-default")

    /**
     * "document-format-details-supported" as defined in:
     * [PWG5100.7](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext10-20031031-5100.7.pdf)
     */
    @JvmField val documentFormatDetailsSupported = DocumentFormatDetails.Type("document-format-details-supported")

    /**
     * "document-format-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val documentFormatSupported = StringType(Tag.mimeMediaType, "document-format-supported")

    /**
     * "document-password-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val documentPasswordSupported = IntegerType("document-password-supported")

    /**
     * "feed-orientation-default" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val feedOrientationDefault = FeedOrientation.Type("feed-orientation-default")

    /**
     * "feed-orientation-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val feedOrientationSupported = FeedOrientation.Type("feed-orientation-supported")

    /**
     * "finishings-col-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val finishingsColSupported = FinishingsCol.Type("finishings-col-supported")

    /**
     * "finishings-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val finishingsDefault = Finishings.Type("finishings-default")

    /**
     * "finishings-ready" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val finishingsReady = Finishings.Type("finishings-ready")

    /**
     * "finishings-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val finishingsSupported = Finishings.Type("finishings-supported")

    /**
     * "folding-direction-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val foldingDirectionSupported = FoldingDirection.Type("folding-direction-supported")

    /**
     * "folding-offset-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val foldingOffsetSupported = RangeOfIntegerType("folding-offset-supported")

    /**
     * "folding-offset-supported(extension)" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val foldingOffsetSupported(Extension) = RangeOfIntegerType("folding-offset-supported(extension)")

    /**
     * "folding-reference-edge-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val foldingReferenceEdgeSupported = FoldingReferenceEdge.Type("folding-reference-edge-supported")

    /**
     * "font-size-requested-default" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val fontSizeRequestedDefault = IntegerType("font-size-requested-default")

    /**
     * "font-size-requested-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val fontSizeRequestedSupported = RangeOfIntegerType("font-size-requested-supported")

    /**
     * "force-front-side-default (under review)" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val forceFrontSideDefault(UnderReview) = IntegerType("force-front-side-default (under review)")

    /**
     * "force-front-side-supported (under review)" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val forceFrontSideSupported(UnderReview) = RangeOfIntegerType("force-front-side-supported (under review)")

    /**
     * "from-name-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val fromNameSupported = IntegerType("from-name-supported")

    /**
     * "identify-actions-default" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val identifyActionsDefault = IdentifyActions.Type("identify-actions-default")

    /**
     * "identify-actions-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val identifyActionsSupported = IdentifyActions.Type("identify-actions-supported")

    /**
     * "imposition-template-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val impositionTemplateDefault = ImpositionTemplate.Type("imposition-template-default")

    /**
     * "imposition-template-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val impositionTemplateSupported = ImpositionTemplate.Type("imposition-template-supported")

    /**
     * "input-color-mode-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val inputColorModeSupported = InputColorMode.Type("input-color-mode-supported")

    /**
     * "input-content-type-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val inputContentTypeSupported = InputContentType.Type("input-content-type-supported")

    /**
     * "input-film-scan-mode-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val inputFilmScanModeSupported = InputFilmScanMode.Type("input-film-scan-mode-supported")

    /**
     * "input-media-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val inputMediaSupported = InputMedia.Type("input-media-supported")

    /**
     * "input-orientation-requested-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val inputOrientationRequestedSupported = Orientation.Type("input-orientation-requested-supported")

    /**
     * "input-quality-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val inputQualitySupported = PrintQuality.Type("input-quality-supported")

    /**
     * "input-resolution-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val inputResolutionSupported = ResolutionType("input-resolution-supported")

    /**
     * "input-sides-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val inputSidesSupported = Sides.Type("input-sides-supported")

    /**
     * "input-source-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val inputSourceSupported = InputSource.Type("input-source-supported")

    /**
     * "insert-after-page-number-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val insertAfterPageNumberSupported = RangeOfIntegerType("insert-after-page-number-supported")

    /**
     * "insert-count-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val insertCountSupported = RangeOfIntegerType("insert-count-supported")

    /**
     * "ipp-features-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val ippFeaturesSupported = IppFeatures.Type("ipp-features-supported")

    /**
     * "ipp-versions-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val ippVersionsSupported = IppVersions.Type("ipp-versions-supported")

    /**
     * "ippget-event-life" as defined in:
     * [RFC3996](http://www.iana.org/go/rfc3996)
     */
    @JvmField val ippgetEventLife = IntegerType("ippget-event-life")

    /**
     * "job-account-id-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val jobAccountIdSupported = BooleanType("job-account-id-supported")

    /**
     * "job-account-type-default" as defined in:
     * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
     */
    @JvmField val jobAccountTypeDefault = JobAccountType.Type("job-account-type-default")

    /**
     * "job-account-type-supported" as defined in:
     * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
     */
    @JvmField val jobAccountTypeSupported = JobAccountType.Type("job-account-type-supported")

    /**
     * "job-accounting-user-id-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val jobAccountingUserIdSupported = BooleanType("job-accounting-user-id-supported")

    /**
     * "job-authorization-uri-supported" as defined in:
     * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
     */
    @JvmField val jobAuthorizationUriSupported = BooleanType("job-authorization-uri-supported")

    /**
     * "job-copies-default" as defined in:
     * [PWG5100.5](http://ftp.pwg.org/pub/pwg/candidates/cs-ippdocobject10-20031031-5100.5.pdf)
     */
    @JvmField val jobCopiesDefault = IntegerType("job-copies-default")

    /**
     * "job-copies-supported" as defined in:
     * [PWG5100.5](http://ftp.pwg.org/pub/pwg/candidates/cs-ippdocobject10-20031031-5100.5.pdf)
     */
    @JvmField val jobCopiesSupported = RangeOfIntegerType("job-copies-supported")

    /**
     * "job-cover-back-supported" as defined in:
     * [PWG5100.5](http://ftp.pwg.org/pub/pwg/candidates/cs-ippdocobject10-20031031-5100.5.pdf)
     */
    @JvmField val jobCoverBackSupported = CoverBack.Type("job-cover-back-supported")

    /**
     * "job-cover-front-supported" as defined in:
     * [PWG5100.5](http://ftp.pwg.org/pub/pwg/candidates/cs-ippdocobject10-20031031-5100.5.pdf)
     */
    @JvmField val jobCoverFrontSupported = CoverBack.Type("job-cover-front-supported")

    /**
     * "job-delay-output-until-default" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobDelayOutputUntilDefault = JobDelayOutputUntil.Type("job-delay-output-until-default")

    /**
     * "job-delay-output-until-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobDelayOutputUntilSupported = JobDelayOutputUntil.Type("job-delay-output-until-supported")

    /**
     * "job-delay-output-until-time-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobDelayOutputUntilTimeSupported = RangeOfIntegerType("job-delay-output-until-time-supported")

    /**
     * "job-destination-spooling-supported" as defined in:
     * [PWG5100.17](http://ftp.pwg.org/pub/pwg/candidates/cs-ippscan10-20140918-5100.17.pdf)
     */
    @JvmField val jobDestinationSpoolingSupported = JobDestinationSpooling.Type("job-destination-spooling-supported")

    /**
     * "job-error-action-default" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val jobErrorActionDefault = JobErrorAction.Type("job-error-action-default")

    /**
     * "job-error-action-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val jobErrorActionSupported = JobErrorAction.Type("job-error-action-supported")

    /**
     * "job-finishings-col-supported" as defined in:
     * [PWG5100.5](http://ftp.pwg.org/pub/pwg/candidates/cs-ippdocobject10-20031031-5100.5.pdf)
     */
    @JvmField val jobFinishingsColSupported = FinishingsCol.Type("job-finishings-col-supported")

    /**
     * "job-finishings-default" as defined in:
     * [PWG5100.5](http://ftp.pwg.org/pub/pwg/candidates/cs-ippdocobject10-20031031-5100.5.pdf)
     */
    @JvmField val jobFinishingsDefault = Finishings.Type("job-finishings-default")

    /**
     * "job-finishings-ready" as defined in:
     * [PWG5100.7](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext10-20031031-5100.7.pdf)
     */
    @JvmField val jobFinishingsReady = Finishings.Type("job-finishings-ready")

    /**
     * "job-finishings-supported" as defined in:
     * [PWG5100.5](http://ftp.pwg.org/pub/pwg/candidates/cs-ippdocobject10-20031031-5100.5.pdf)
     */
    @JvmField val jobFinishingsSupported = Finishings.Type("job-finishings-supported")

    /**
     * "job-hold-until-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val jobHoldUntilDefault = JobHoldUntil.Type("job-hold-until-default")

    /**
     * "job-hold-until-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val jobHoldUntilSupported = JobHoldUntil.Type("job-hold-until-supported")

    /**
     * "job-hold-until-time-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobHoldUntilTimeSupported = RangeOfIntegerType("job-hold-until-time-supported")

    /**
     * "job-ids-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobIdsSupported = BooleanType("job-ids-supported")

    /**
     * "job-impressions-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val jobImpressionsSupported = RangeOfIntegerType("job-impressions-supported")

    /**
     * "job-k-octets-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val jobKOctetsSupported = RangeOfIntegerType("job-k-octets-supported")

    /**
     * "job-media-sheets-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val jobMediaSheetsSupported = RangeOfIntegerType("job-media-sheets-supported")

    /**
     * "job-message-to-operator-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val jobMessageToOperatorSupported = BooleanType("job-message-to-operator-supported")

    /**
     * "job-pages-per-set-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val jobPagesPerSetSupported = BooleanType("job-pages-per-set-supported")

    /**
     * "job-password-encryption-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobPasswordEncryptionSupported = JobPasswordEncryption.Type("job-password-encryption-supported")

    /**
     * "job-password-length-supported" as defined in:
     * [IPPWG20160229-1](http://ftp.pwg.org/pub/pwg/ipp/wd/wp-job-password-repertoire-20160101.pdf)
     */
    @JvmField val jobPasswordLengthSupported = RangeOfIntegerType("job-password-length-supported")

    /**
     * "job-password-repertoire-configured" as defined in:
     * [IPPWG20160229-1](http://ftp.pwg.org/pub/pwg/ipp/wd/wp-job-password-repertoire-20160101.pdf)
     */
    @JvmField val jobPasswordRepertoireConfigured = JobPasswordRepertoire.Type("job-password-repertoire-configured")

    /**
     * "job-password-repertoire-supported" as defined in:
     * [IPPWG20160229-1](http://ftp.pwg.org/pub/pwg/ipp/wd/wp-job-password-repertoire-20160101.pdf)
     */
    @JvmField val jobPasswordRepertoireSupported = JobPasswordRepertoire.Type("job-password-repertoire-supported")

    /**
     * "job-password-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobPasswordSupported = IntegerType("job-password-supported")

    /**
     * "job-phone-number-default" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobPhoneNumberDefault = UriType("job-phone-number-default")

    /**
     * "job-phone-number-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobPhoneNumberSupported = BooleanType("job-phone-number-supported")

    /**
     * "job-priority-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val jobPriorityDefault = IntegerType("job-priority-default")

    /**
     * "job-priority-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val jobPrioritySupported = IntegerType("job-priority-supported")

    /**
     * "job-recipient-name-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobRecipientNameSupported = BooleanType("job-recipient-name-supported")

    /**
     * "job-sheet-message-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val jobSheetMessageSupported = BooleanType("job-sheet-message-supported")

    /**
     * "job-sheets-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val jobSheetsDefault = JobSheets.Type("job-sheets-default")

    /**
     * "job-sheets-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val jobSheetsSupported = JobSheets.Type("job-sheets-supported")

    /**
     * "job-spooling-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val jobSpoolingSupported = JobSpooling.Type("job-spooling-supported")

    /**
     * "jpeg-features-supported" as defined in:
     * [APPLE20151021](http://www.pwg.org/pipermail/ipp/2015/018634.html)
     */
    @JvmField val jpegFeaturesSupported = JpegFeatures.Type("jpeg-features-supported")

    /**
     * "jpeg-k-octets-supported" as defined in:
     * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
     */
    @JvmField val jpegKOctetsSupported = RangeOfIntegerType("jpeg-k-octets-supported")

    /**
     * "jpeg-x-dimension-supported" as defined in:
     * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
     */
    @JvmField val jpegXDimensionSupported = RangeOfIntegerType("jpeg-x-dimension-supported")

    /**
     * "jpeg-y-dimension-supported" as defined in:
     * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
     */
    @JvmField val jpegYDimensionSupported = RangeOfIntegerType("jpeg-y-dimension-supported")

    /**
     * "laminating-sides-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val laminatingSidesSupported = LaminatingSides.Type("laminating-sides-supported")

    /**
     * "laminating-type-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val laminatingTypeSupported = LaminatingType.Type("laminating-type-supported")

    /**
     * "logo-uri-formats-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val logoUriFormatsSupported = StringType(Tag.mimeMediaType, "logo-uri-formats-supported")

    /**
     * "logo-uri-schemes-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val logoUriSchemesSupported = UriType("logo-uri-schemes-supported")

    /**
     * "material-amount-units-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val materialAmountUnitsSupported = MaterialAmountUnits.Type("material-amount-units-supported")

    /**
     * "material-diameter-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val materialDiameterSupported = RangeOfIntegerType("material-diameter-supported")

    /**
     * "material-purpose-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val materialPurposeSupported = MaterialPurpose.Type("material-purpose-supported")

    /**
     * "material-rate-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val materialRateSupported = RangeOfIntegerType("material-rate-supported")

    /**
     * "material-rate-units-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val materialRateUnitsSupported = MaterialRateUnits.Type("material-rate-units-supported")

    /**
     * "material-shell-thickness-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val materialShellThicknessSupported = RangeOfIntegerType("material-shell-thickness-supported")

    /**
     * "material-temperature-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val materialTemperatureSupported = RangeOfIntegerType("material-temperature-supported")

    /**
     * "material-type-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val materialTypeSupported = MaterialType.Type("material-type-supported")

    /**
     * "materials-col-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val materialsColSupported = MaterialsColSupported.Type("materials-col-supported")

    /**
     * "max-materials-col-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val maxMaterialsColSupported = IntegerType("max-materials-col-supported")

    /**
     * "max-save-info-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val maxSaveInfoSupported = IntegerType("max-save-info-supported")

    /**
     * "max-stitching-locations-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val maxStitchingLocationsSupported = IntegerType("max-stitching-locations-supported")

    /**
     * "media-back-coating-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaBackCoatingSupported = MediaBackCoating.Type("media-back-coating-supported")

    /**
     * "media-bottom-margin-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val mediaBottomMarginSupported = IntegerType("media-bottom-margin-supported")

    /**
     * "media-col-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaColSupported = MediaCol.Type("media-col-supported")

    /**
     * "media-color-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaColorSupported = MediaColor.Type("media-color-supported")

    /**
     * "media-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val mediaDefault = Media.Type("media-default")

    /**
     * "media-front-coating-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaFrontCoatingSupported = MediaBackCoating.Type("media-front-coating-supported")

    /**
     * "media-grain-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val mediaGrainSupported = MediaGrain.Type("media-grain-supported")

    /**
     * "media-hole-count-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaHoleCountSupported = RangeOfIntegerType("media-hole-count-supported")

    /**
     * "media-info-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaInfoSupported = BooleanType("media-info-supported")

    /**
     * "media-left-margin-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val mediaLeftMarginSupported = IntegerType("media-left-margin-supported")

    /**
     * "media-order-count-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaOrderCountSupported = RangeOfIntegerType("media-order-count-supported")

    /**
     * "media-pre-printed-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaPrePrintedSupported = MediaPrePrinted.Type("media-pre-printed-supported")

    /**
     * "media-ready" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val mediaReady = MediaReady.Type("media-ready")

    /**
     * "media-recycled-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaRecycledSupported = MediaRecycled.Type("media-recycled-supported")

    /**
     * "media-right-margin-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val mediaRightMarginSupported = IntegerType("media-right-margin-supported")

    /**
     * "media-source-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val mediaSourceSupported = MediaSource.Type("media-source-supported")

    /**
     * "media-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val mediaSupported = Media.Type("media-supported")

    /**
     * "media-thickness-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val mediaThicknessSupported = RangeOfIntegerType("media-thickness-supported")

    /**
     * "media-tooth-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val mediaToothSupported = MediaTooth.Type("media-tooth-supported")

    /**
     * "media-top-margin-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val mediaTopMarginSupported = IntegerType("media-top-margin-supported")

    /**
     * "media-type-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaTypeSupported = MediaType.Type("media-type-supported")

    /**
     * "media-weight-metric-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val mediaWeightMetricSupported = RangeOfIntegerType("media-weight-metric-supported")

    /**
     * "message-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val messageSupported = IntegerType("message-supported")

    /**
     * "multiple-destination-uris-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val multipleDestinationUrisSupported = BooleanType("multiple-destination-uris-supported")

    /**
     * "multiple-document-handling-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val multipleDocumentHandlingDefault = MultipleDocumentHandling.Type("multiple-document-handling-default")

    /**
     * "multiple-document-handling-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val multipleDocumentHandlingSupported = MultipleDocumentHandling.Type("multiple-document-handling-supported")

    /**
     * "multiple-document-jobs-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val multipleDocumentJobsSupported = BooleanType("multiple-document-jobs-supported")

    /**
     * "multiple-object-handling-default" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val multipleObjectHandlingDefault = MultipleObjectHandling.Type("multiple-object-handling-default")

    /**
     * "multiple-object-handling-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val multipleObjectHandlingSupported = MultipleObjectHandling.Type("multiple-object-handling-supported")

    /**
     * "multiple-operation-time-out" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val multipleOperationTimeOut = IntegerType("multiple-operation-time-out")

    /**
     * "multiple-operation-time-out-action" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val multipleOperationTimeOutAction = MultipleOperationTimeOutAction.Type("multiple-operation-time-out-action")

    /**
     * "notify-events-default" as defined in:
     * [RFC3995](http://www.iana.org/go/rfc3995)
     */
    @JvmField val notifyEventsDefault = NotifyEvents.Type("notify-events-default")

    /**
     * "notify-events-supported" as defined in:
     * [RFC3995](http://www.iana.org/go/rfc3995)
     */
    @JvmField val notifyEventsSupported = NotifyEvents.Type("notify-events-supported")

    /**
     * "notify-lease-duration-default" as defined in:
     * [RFC3995](http://www.iana.org/go/rfc3995)
     */
    @JvmField val notifyLeaseDurationDefault = IntegerType("notify-lease-duration-default")

    /**
     * "notify-lease-duration-supported" as defined in:
     * [RFC3995](http://www.iana.org/go/rfc3995)
     */
    @JvmField val notifyLeaseDurationSupported = RangeOfIntegerType("notify-lease-duration-supported")

    /**
     * "notify-pull-method-supported" as defined in:
     * [RFC3995](http://www.iana.org/go/rfc3995)
     */
    @JvmField val notifyPullMethodSupported = NotifyPullMethod.Type("notify-pull-method-supported")

    /**
     * "notify-schemes-supported" as defined in:
     * [RFC3995](http://www.iana.org/go/rfc3995)
     */
    @JvmField val notifySchemesSupported = UriType("notify-schemes-supported")

    /**
     * "number-of-retries-default" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val numberOfRetriesDefault = IntegerType("number-of-retries-default")

    /**
     * "number-of-retries-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val numberOfRetriesSupported = RangeOfIntegerType("number-of-retries-supported")

    /**
     * "number-up-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val numberUpDefault = IntegerType("number-up-default")

    /**
     * "number-up-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val numberUpSupported = RangeOfIntegerType("number-up-supported")

    /**
     * "oauth-authorization-server-uri" as defined in:
     * [PWG5100.18](http://ftp.pwg.org/pub/pwg/candidates/cs-ippinfra10-20150619-5100.18.pdf)
     */
    @JvmField val oauthAuthorizationServerUri = UriType("oauth-authorization-server-uri")

    /**
     * "operations-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val operationsSupported = Operations.Type("operations-supported")

    /**
     * "organization-name-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val organizationNameSupported = IntegerType("organization-name-supported")

    /**
     * "orientation-requested-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val orientationRequestedDefault = Orientation.Type("orientation-requested-default")

    /**
     * "orientation-requested-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val orientationRequestedSupported = Orientation.Type("orientation-requested-supported")

    /**
     * "output-bin-default" as defined in:
     * [PWG5100.2](http://ftp.pwg.org/pub/pwg/candidates/cs-ippoutputbin10-20010207-5100.2.pdf)
     */
    @JvmField val outputBinDefault = OutputBin.Type("output-bin-default")

    /**
     * "output-bin-supported" as defined in:
     * [PWG5100.2](http://ftp.pwg.org/pub/pwg/candidates/cs-ippoutputbin10-20010207-5100.2.pdf)
     */
    @JvmField val outputBinSupported = OutputBin.Type("output-bin-supported")

    /**
     * "output-device-uuid-supported" as defined in:
     * [PWG5100.18](http://ftp.pwg.org/pub/pwg/candidates/cs-ippinfra10-20150619-5100.18.pdf)
     */
    @JvmField val outputDeviceUuidSupported = UriType("output-device-uuid-supported")

    /**
     * "page-delivery-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val pageDeliveryDefault = PageDelivery.Type("page-delivery-default")

    /**
     * "page-delivery-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val pageDeliverySupported = PageDelivery.Type("page-delivery-supported")

    /**
     * "page-order-received-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val pageOrderReceivedDefault = PageOrderReceived.Type("page-order-received-default")

    /**
     * "page-order-received-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val pageOrderReceivedSupported = PageOrderReceived.Type("page-order-received-supported")

    /**
     * "page-ranges-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val pageRangesSupported = BooleanType("page-ranges-supported")

    /**
     * "pages-per-subset-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val pagesPerSubsetSupported = BooleanType("pages-per-subset-supported")

    /**
     * "parent-printers-supported" as defined in:
     * [RFC3998](http://www.iana.org/go/rfc3998)
     */
    @JvmField val parentPrintersSupported = UriType("parent-printers-supported")

    /**
     * "pdf-features-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val pdfFeaturesSupported = PdfFeatures.Type("pdf-features-supported")

    /**
     * "pdf-k-octets-supported" as defined in:
     * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
     */
    @JvmField val pdfKOctetsSupported = RangeOfIntegerType("pdf-k-octets-supported")

    /**
     * "pdf-versions-supported" as defined in:
     * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
     */
    @JvmField val pdfVersionsSupported = PdfVersions.Type("pdf-versions-supported")

    /**
     * "pdl-init-file-location-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val pdlInitFileLocationSupported = UriType("pdl-init-file-location-supported")

    /**
     * "pdl-init-file-name-subdirectory-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val pdlInitFileNameSubdirectorySupported = BooleanType("pdl-init-file-name-subdirectory-supported")

    /**
     * "pdl-init-file-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val pdlInitFileSupported = PdlInitFile.Type("pdl-init-file-supported")

    /**
     * "pdl-override-guaranteed-supported" as defined in:
     * [IPPWG20151019](http://www.pwg.org/archives/ipp/2015/018629.html)
     */
    @JvmField val pdlOverrideGuaranteedSupported = PdlOverrideGuaranteedSupported.Type("pdl-override-guaranteed-supported")

    /**
     * "pdl-override-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val pdlOverrideSupported = PdlOverride.Type("pdl-override-supported")

    /**
     * "platform-shape" as defined in:
     * [APPLE20170629](http://www.pwg.org/pipermail/ipp/2017/019246.html)
     */
    @JvmField val platformShape = PlatformShape.Type("platform-shape")

    /**
     * "platform-temperature-default" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val platformTemperatureDefault = IntegerType("platform-temperature-default")

    /**
     * "platform-temperature-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val platformTemperatureSupported = RangeOfIntegerType("platform-temperature-supported")

    /**
     * "preferred-attributes-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val preferredAttributesSupported = BooleanType("preferred-attributes-supported")

    /**
     * "presentation-direction-number-up-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val presentationDirectionNumberUpDefault = PresentationDirectionNumberUp.Type("presentation-direction-number-up-default")

    /**
     * "presentation-direction-number-up-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val presentationDirectionNumberUpSupported = PresentationDirectionNumberUp.Type("presentation-direction-number-up-supported")

    /**
     * "print-base-default" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val printBaseDefault = PrintBase.Type("print-base-default")

    /**
     * "print-base-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val printBaseSupported = PrintBase.Type("print-base-supported")

    /**
     * "print-color-mode-default" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val printColorModeDefault = PrintColorMode.Type("print-color-mode-default")

    /**
     * "print-color-mode-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val printColorModeSupported = PrintColorMode.Type("print-color-mode-supported")

    /**
     * "print-content-optimize-default" as defined in:
     * [PWG5100.7](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext10-20031031-5100.7.pdf)
     */
    @JvmField val printContentOptimizeDefault = PrintContentOptimize.Type("print-content-optimize-default")

    /**
     * "print-content-optimize-supported" as defined in:
     * [PWG5100.7](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext10-20031031-5100.7.pdf)
     */
    @JvmField val printContentOptimizeSupported = PrintContentOptimize.Type("print-content-optimize-supported")

    /**
     * "print-objects-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val printObjectsSupported = PrintObjectsSupported.Type("print-objects-supported")

    /**
     * "print-quality-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val printQualityDefault = PrintQuality.Type("print-quality-default")

    /**
     * "print-quality-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val printQualitySupported = PrintQuality.Type("print-quality-supported")

    /**
     * "print-rendering-intent-default" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val printRenderingIntentDefault = PrintRenderingIntent.Type("print-rendering-intent-default")

    /**
     * "print-rendering-intent-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val printRenderingIntentSupported = PrintRenderingIntent.Type("print-rendering-intent-supported")

    /**
     * "print-scaling-default" as defined in:
     * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
     */
    @JvmField val printScalingDefault = PrintScaling.Type("print-scaling-default")

    /**
     * "print-scaling-supported" as defined in:
     * [PWG5100.16](http://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf)
     */
    @JvmField val printScalingSupported = PrintScaling.Type("print-scaling-supported")

    /**
     * "print-supports-default" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val printSupportsDefault = PrintSupports.Type("print-supports-default")

    /**
     * "print-supports-supported" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val printSupportsSupported = PrintSupports.Type("print-supports-supported")

    /**
     * "printer-camera-image-uri" as defined in:
     * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf)
     */
    @JvmField val printerCameraImageUri = UriType("printer-camera-image-uri")

    /**
     * "printer-charge-info-uri" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val printerChargeInfoUri = UriType("printer-charge-info-uri")

    /**
     * "printer-driver-installer" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val printerDriverInstaller = UriType("printer-driver-installer")

    /**
     * "printer-fax-log-uri" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val printerFaxLogUri = UriType("printer-fax-log-uri")

    /**
     * "printer-fax-modem-number" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val printerFaxModemNumber = UriType("printer-fax-modem-number")

    /**
     * "printer-geo-location" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val printerGeoLocation = UriType("printer-geo-location")

    /**
     * "printer-icons" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val printerIcons = UriType("printer-icons")

    /**
     * "printer-more-info-manufacturer" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val printerMoreInfoManufacturer = UriType("printer-more-info-manufacturer")

    /**
     * "printer-resolution-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val printerResolutionDefault = ResolutionType("printer-resolution-default")

    /**
     * "printer-resolution-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val printerResolutionSupported = ResolutionType("printer-resolution-supported")

    /**
     * "printer-static-resource-directory-uri" as defined in:
     * [PWG5100.18](http://ftp.pwg.org/pub/pwg/candidates/cs-ippinfra10-20150619-5100.18.pdf)
     */
    @JvmField val printerStaticResourceDirectoryUri = UriType("printer-static-resource-directory-uri")

    /**
     * "printer-static-resource-k-octets-supported" as defined in:
     * [PWG5100.18](http://ftp.pwg.org/pub/pwg/candidates/cs-ippinfra10-20150619-5100.18.pdf)
     */
    @JvmField val printerStaticResourceKOctetsSupported = IntegerType("printer-static-resource-k-octets-supported")

    /**
     * "printer-strings-uri" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val printerStringsUri = UriType("printer-strings-uri")

    /**
     * "proof-print-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val proofPrintSupported = ProofPrint.Type("proof-print-supported")

    /**
     * "punching-hole-diameter-configured" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val punchingHoleDiameterConfigured = IntegerType("punching-hole-diameter-configured")

    /**
     * "punching-locations-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val punchingLocationsSupported = RangeOfIntegerType("punching-locations-supported")

    /**
     * "punching-offset-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val punchingOffsetSupported = RangeOfIntegerType("punching-offset-supported")

    /**
     * "punching-reference-edge-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val punchingReferenceEdgeSupported = PunchingReferenceEdge.Type("punching-reference-edge-supported")

    /**
     * "pwg-raster-document-resolution-supported" as defined in:
     * [PWG5102.4](http://ftp.pwg.org/pub/pwg/candidates/cs-ippraster10-20120420-5102.4.pdf)
     */
    @JvmField val pwgRasterDocumentResolutionSupported = ResolutionType("pwg-raster-document-resolution-supported")

    /**
     * "pwg-raster-document-sheet-back" as defined in:
     * [PWG5102.4](http://ftp.pwg.org/pub/pwg/candidates/cs-ippraster10-20120420-5102.4.pdf)
     */
    @JvmField val pwgRasterDocumentSheetBack = PwgRasterDocumentSheetBack.Type("pwg-raster-document-sheet-back")

    /**
     * "pwg-raster-document-type-supported" as defined in:
     * [PWG5102.4](http://ftp.pwg.org/pub/pwg/candidates/cs-ippraster10-20120420-5102.4.pdf)
     */
    @JvmField val pwgRasterDocumentTypeSupported = PwgRasterDocumentType.Type("pwg-raster-document-type-supported")

    /**
     * "reference-uri-schemes-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val referenceUriSchemesSupported = UriType("reference-uri-schemes-supported")

    /**
     * "requesting-user-uri-supported" as defined in:
     * [PWG5100.13](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf)
     */
    @JvmField val requestingUserUriSupported = BooleanType("requesting-user-uri-supported")

    /**
     * "retry-interval-default" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val retryIntervalDefault = IntegerType("retry-interval-default")

    /**
     * "retry-interval-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val retryIntervalSupported = RangeOfIntegerType("retry-interval-supported")

    /**
     * "retry-time-out-default" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val retryTimeOutDefault = IntegerType("retry-time-out-default")

    /**
     * "retry-time-out-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val retryTimeOutSupported = RangeOfIntegerType("retry-time-out-supported")

    /**
     * "save-disposition-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val saveDispositionSupported = SaveDisposition.Type("save-disposition-supported")

    /**
     * "save-document-format-default" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val saveDocumentFormatDefault = StringType(Tag.mimeMediaType, "save-document-format-default")

    /**
     * "save-document-format-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val saveDocumentFormatSupported = StringType(Tag.mimeMediaType, "save-document-format-supported")

    /**
     * "save-location-default" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val saveLocationDefault = UriType("save-location-default")

    /**
     * "save-location-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val saveLocationSupported = UriType("save-location-supported")

    /**
     * "save-name-subdirectory-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val saveNameSubdirectorySupported = BooleanType("save-name-subdirectory-supported")

    /**
     * "save-name-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val saveNameSupported = BooleanType("save-name-supported")

    /**
     * "sheet-collate-default" as defined in:
     * [RFC3381](http://www.iana.org/go/rfc3381)
     */
    @JvmField val sheetCollateDefault = SheetCollate.Type("sheet-collate-default")

    /**
     * "sheet-collate-supported" as defined in:
     * [RFC3381](http://www.iana.org/go/rfc3381)
     */
    @JvmField val sheetCollateSupported = SheetCollate.Type("sheet-collate-supported")

    /**
     * "sides-default" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val sidesDefault = Sides.Type("sides-default")

    /**
     * "sides-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val sidesSupported = Sides.Type("sides-supported")

    /**
     * "stitching-angle-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val stitchingAngleSupported = RangeOfIntegerType("stitching-angle-supported")

    /**
     * "stitching-locations-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val stitchingLocationsSupported = RangeOfIntegerType("stitching-locations-supported")

    /**
     * "stitching-method-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val stitchingMethodSupported = StitchingMethod.Type("stitching-method-supported")

    /**
     * "stitching-offset-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val stitchingOffsetSupported = RangeOfIntegerType("stitching-offset-supported")

    /**
     * "stitching-reference-edge-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val stitchingReferenceEdgeSupported = StitchingReferenceEdge.Type("stitching-reference-edge-supported")

    /**
     * "subject-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val subjectSupported = IntegerType("subject-supported")

    /**
     * "subordinate-printers-supported" as defined in:
     * [RFC3998](http://www.iana.org/go/rfc3998)
     */
    @JvmField val subordinatePrintersSupported = UriType("subordinate-printers-supported")

    /**
     * "to-name-supported" as defined in:
     * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf)
     */
    @JvmField val toNameSupported = IntegerType("to-name-supported")

    /**
     * "trimming-offset-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val trimmingOffsetSupported = RangeOfIntegerType("trimming-offset-supported")

    /**
     * "trimming-reference-edge-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val trimmingReferenceEdgeSupported = TrimmingReferenceEdge.Type("trimming-reference-edge-supported")

    /**
     * "trimming-type-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val trimmingTypeSupported = TrimmingType.Type("trimming-type-supported")

    /**
     * "trimming-when-supported" as defined in:
     * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf)
     */
    @JvmField val trimmingWhenSupported = TrimmingWhen.Type("trimming-when-supported")

    /**
     * "uri-authentication-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val uriAuthenticationSupported = UriAuthentication.Type("uri-authentication-supported")

    /**
     * "uri-security-supported" as defined in:
     * [RFC8011](http://www.iana.org/go/rfc8011)
     */
    @JvmField val uriSecuritySupported = UriSecurity.Type("uri-security-supported")

    /**
     * "which-jobs-supported" as defined in:
     * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf)
     */
    @JvmField val whichJobsSupported = WhichJobs.Type("which-jobs-supported")

    /**
     * "x-image-position-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val xImagePositionDefault = XImagePosition.Type("x-image-position-default")

    /**
     * "x-image-position-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val xImagePositionSupported = XImagePosition.Type("x-image-position-supported")

    /**
     * "x-image-shift-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val xImageShiftDefault = IntegerType("x-image-shift-default")

    /**
     * "x-image-shift-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val xImageShiftSupported = RangeOfIntegerType("x-image-shift-supported")

    /**
     * "x-side1-image-shift-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val xSide1ImageShiftDefault = IntegerType("x-side1-image-shift-default")

    /**
     * "x-side1-image-shift-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val xSide1ImageShiftSupported = RangeOfIntegerType("x-side1-image-shift-supported")

    /**
     * "x-side2-image-shift-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val xSide2ImageShiftDefault = IntegerType("x-side2-image-shift-default")

    /**
     * "x-side2-image-shift-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val xSide2ImageShiftSupported = RangeOfIntegerType("x-side2-image-shift-supported")

    /**
     * "y-image-position-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val yImagePositionDefault = YImagePosition.Type("y-image-position-default")

    /**
     * "y-image-position-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val yImagePositionSupported = YImagePosition.Type("y-image-position-supported")

    /**
     * "y-image-shift-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val yImageShiftDefault = IntegerType("y-image-shift-default")

    /**
     * "y-image-shift-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val yImageShiftSupported = RangeOfIntegerType("y-image-shift-supported")

    /**
     * "y-side1-image-shift-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val ySide1ImageShiftDefault = IntegerType("y-side1-image-shift-default")

    /**
     * "y-side1-image-shift-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val ySide1ImageShiftSupported = RangeOfIntegerType("y-side1-image-shift-supported")

    /**
     * "y-side2-image-shift-default" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val ySide2ImageShiftDefault = IntegerType("y-side2-image-shift-default")

    /**
     * "y-side2-image-shift-supported" as defined in:
     * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
     */
    @JvmField val ySide2ImageShiftSupported = RangeOfIntegerType("y-side2-image-shift-supported")

    /** All known attributes */
    @JvmField
    val all = PrinterDescription::class.java.getStaticObjects()
            .filter { it is AttributeType<*> }
            .map { it as AttributeType<*> }
}