// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "printer-volume-supported" collection as defined in:
 * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class PrinterVolumeSupported
@JvmOverloads constructor(
    val xDimension: Int? = null,
    val yDimension: Int? = null,
    val zDimension: Int? = null,
    val _extras: List<Attribute<*>> = listOf()
) : HasAttributeCollection {

    /** Generate attribute list */
    override val attributes: AttributeCollection by lazy {
        AttributeCollection(mutableListOf<Attribute<*>>().apply {
            xDimension?.also {
                add(Members.xDimension.of(it))
            }
            yDimension?.also {
                add(Members.yDimension.of(it))
            }
            zDimension?.also {
                add(Members.zDimension.of(it))
            }
        } + _extras)
    }

    /** Type for attributes of this collection */
    class Type(name: String): TypedCollectionType<PrinterVolumeSupported>(Members, name)

    companion object Members : CollectionParser<PrinterVolumeSupported> {
        override val typeName = PrinterVolumeSupported::class.java.simpleName!!
        override fun fromAttributes(attributes: List<Attribute<*>>): PrinterVolumeSupported {
            val remain = attributes.toMutableList()
            return PrinterVolumeSupported(
                extractOne(remain, xDimension),
                extractOne(remain, yDimension),
                extractOne(remain, zDimension),
                _extras = remain)
        }
        /** "x-dimension" member type */
        @JvmField val xDimension = IntegerType("x-dimension")
        /** "y-dimension" member type */
        @JvmField val yDimension = IntegerType("y-dimension")
        /** "z-dimension" member type */
        @JvmField val zDimension = IntegerType("z-dimension")
    }

    /**
     * All allowed member names in keyword form.
     */
    data class Keywords(
        override val value: String
    ) : Keyword() {
        override fun toString() = value
        /** An attribute type for [PrinterVolumeSupported] member names as keywords */
        class Type(name: String) : KeywordType<Keywords>(Encoder, name)

        companion object {
            /** "x-dimension" member type */
            @JvmField val xDimension = Keywords(Members.xDimension.name)
            /** "y-dimension" member type */
            @JvmField val yDimension = Keywords(Members.yDimension.name)
            /** "z-dimension" member type */
            @JvmField val zDimension = Keywords(Members.zDimension.name)

            @JvmField val Encoder = KeywordType.encoderOf(Keywords::class.java) { value, _, _ ->
                Keywords(value)
            }
        }
    }
}
