// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "proof-print" collection as defined in:
 * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class ProofPrint
@JvmOverloads constructor(
    val media: Media? = null,
    val mediaCol: MediaCol? = null,
    val proofPrintCopies: Int? = null,
    val _extras: List<Attribute<*>> = listOf()
) : HasAttributeCollection {

    /** Generate attribute list */
    override val attributes: AttributeCollection by lazy {
        AttributeCollection(mutableListOf<Attribute<*>>().apply {
            media?.also {
                add(Members.media.of(it))
            }
            mediaCol?.also {
                add(Members.mediaCol.of(it))
            }
            proofPrintCopies?.also {
                add(Members.proofPrintCopies.of(it))
            }
        } + _extras)
    }

    /** Type for attributes of this collection */
    class Type(name: String): TypedCollectionType<ProofPrint>(Members, name)

    companion object Members : CollectionParser<ProofPrint> {
        override val typeName = ProofPrint::class.java.simpleName!!
        override fun fromAttributes(attributes: List<Attribute<*>>): ProofPrint {
            val remain = attributes.toMutableList()
            return ProofPrint(
                extractOne(remain, media),
                extractOne(remain, mediaCol),
                extractOne(remain, proofPrintCopies),
                _extras = remain)
        }
        /** "media" member type */
        @JvmField val media = Media.Type("media")
        /** "media-col" member type */
        @JvmField val mediaCol = MediaCol.Type("media-col")
        /** "proof-print-copies" member type */
        @JvmField val proofPrintCopies = IntegerType("proof-print-copies")
    }

    /**
     * All allowed member names in keyword form.
     */
    data class Keywords(
        override val value: String
    ) : Keyword() {
        override fun toString() = value
        /** An attribute type for [ProofPrint] member names as keywords */
        class Type(name: String) : KeywordType<Keywords>(Encoder, name)

        companion object {
            /** "media" member type */
            @JvmField val media = Keywords(Members.media.name)
            /** "media-col" member type */
            @JvmField val mediaCol = Keywords(Members.mediaCol.name)
            /** "proof-print-copies" member type */
            @JvmField val proofPrintCopies = Keywords(Members.proofPrintCopies.name)

            @JvmField val Encoder = KeywordType.encoderOf(Keywords::class.java) { value, _, _ ->
                Keywords(value)
            }
        }
    }
}
