// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "pwg-raster-document-type-supported" keyword as defined in:
 *   * [PWG5102.4](http://ftp.pwg.org/pub/pwg/candidates/cs-ippraster10-20120420-5102.4.pdf)
 */
data class PwgRasterDocumentType(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [PwgRasterDocumentType] attributes */
    class Type(name: String) : KeywordType<PwgRasterDocumentType>(Encoder, name)

    companion object {
        @JvmField val adobeRgb16 = PwgRasterDocumentType("adobe-rgb_16")
        @JvmField val adobeRgb8 = PwgRasterDocumentType("adobe-rgb_8")
        @JvmField val black1 = PwgRasterDocumentType("black_1")
        @JvmField val black16 = PwgRasterDocumentType("black_16")
        @JvmField val black8 = PwgRasterDocumentType("black_8")
        @JvmField val cmyk16 = PwgRasterDocumentType("cmyk_16")
        @JvmField val cmyk8 = PwgRasterDocumentType("cmyk_8")
        @JvmField val device1016 = PwgRasterDocumentType("device10_16")
        @JvmField val device108 = PwgRasterDocumentType("device10_8")
        @JvmField val device1116 = PwgRasterDocumentType("device11_16")
        @JvmField val device118 = PwgRasterDocumentType("device11_8")
        @JvmField val device1216 = PwgRasterDocumentType("device12_16")
        @JvmField val device128 = PwgRasterDocumentType("device12_8")
        @JvmField val device1316 = PwgRasterDocumentType("device13_16")
        @JvmField val device138 = PwgRasterDocumentType("device13_8")
        @JvmField val device1416 = PwgRasterDocumentType("device14_16")
        @JvmField val device148 = PwgRasterDocumentType("device14_8")
        @JvmField val device1516 = PwgRasterDocumentType("device15_16")
        @JvmField val device158 = PwgRasterDocumentType("device15_8")
        @JvmField val device116 = PwgRasterDocumentType("device1_16")
        @JvmField val device18 = PwgRasterDocumentType("device1_8")
        @JvmField val device216 = PwgRasterDocumentType("device2_16")
        @JvmField val device28 = PwgRasterDocumentType("device2_8")
        @JvmField val device316 = PwgRasterDocumentType("device3_16")
        @JvmField val device38 = PwgRasterDocumentType("device3_8")
        @JvmField val device416 = PwgRasterDocumentType("device4_16")
        @JvmField val device48 = PwgRasterDocumentType("device4_8")
        @JvmField val device516 = PwgRasterDocumentType("device5_16")
        @JvmField val device58 = PwgRasterDocumentType("device5_8")
        @JvmField val device616 = PwgRasterDocumentType("device6_16")
        @JvmField val device68 = PwgRasterDocumentType("device6_8")
        @JvmField val device716 = PwgRasterDocumentType("device7_16")
        @JvmField val device78 = PwgRasterDocumentType("device7_8")
        @JvmField val device816 = PwgRasterDocumentType("device8_16")
        @JvmField val device88 = PwgRasterDocumentType("device8_8")
        @JvmField val device916 = PwgRasterDocumentType("device9_16")
        @JvmField val device98 = PwgRasterDocumentType("device9_8")
        @JvmField val rgb16 = PwgRasterDocumentType("rgb_16")
        @JvmField val rgb8 = PwgRasterDocumentType("rgb_8")
        @JvmField val sgray1 = PwgRasterDocumentType("sgray_1")
        @JvmField val sgray16 = PwgRasterDocumentType("sgray_16")
        @JvmField val sgray8 = PwgRasterDocumentType("sgray_8")
        @JvmField val srgb16 = PwgRasterDocumentType("srgb_16")
        @JvmField val srgb8 = PwgRasterDocumentType("srgb_8")
        @JvmField val Encoder = KeywordType.encoderOf(PwgRasterDocumentType::class.java) { value, _, _ ->
            PwgRasterDocumentType(value)
        }
    }
}
