// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.KeywordOrName
import com.hp.jipp.encoding.KeywordType
import com.hp.jipp.encoding.Tag

/**
 * "separator-sheets-type" keyword as defined in:
 *   * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
 *
 * Also used by:
 *   * `separator-sheets-type-supported`
 */
data class SeparatorSheetsType(
    override val value: String,
    override val tag: Tag = Tag.keyword,
    override val language: String? = null
) : KeywordOrName() {

    constructor(value: String): this(value, Tag.keyword)

    override fun toString() = value

    /** An attribute type for [SeparatorSheetsType] attributes */
    class Type(name: String) : KeywordType<SeparatorSheetsType>(Encoder, name)

    companion object {
        @JvmField val bothSheets = SeparatorSheetsType("both-sheets")
        @JvmField val endSheet = SeparatorSheetsType("end-sheet")
        @JvmField val none = SeparatorSheetsType("none")
        @JvmField val slipSheets = SeparatorSheetsType("slip-sheets")
        @JvmField val startSheet = SeparatorSheetsType("start-sheet")
        @JvmField val Encoder = KeywordType.encoderOf(SeparatorSheetsType::class.java) { value, tag, language ->
            SeparatorSheetsType(value, tag, language)
        }
    }
}
