// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "stitching-supported" keyword as defined in:
 *   * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf)
 */
data class Stitching(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [Stitching] attributes */
    class Type(name: String) : KeywordType<Stitching>(Encoder, name)

    companion object {
        @JvmField val stitchingLocations = Stitching("stitching-locations")
        @JvmField val stitchingOffset = Stitching("stitching-offset")
        @JvmField val stitchingReferenceEdge = Stitching("stitching-reference-edge")
        @JvmField val Encoder = KeywordType.encoderOf(Stitching::class.java) { value, _, _ ->
            Stitching(value)
        }
    }
}
