// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "trimming-when" keyword as defined in
 * [PWG5100.1](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings10-20010205-5100.1.pdf).
 *
 * Also used by:
 *   * `trimming-when-supported`
 */
data class TrimmingWhen(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [TrimmingWhen] attributes */
    class Type(name: String) : KeywordType<TrimmingWhen>(Encoder, name)

    companion object {
        @JvmField val afterDocuments = TrimmingWhen("after-documents")
        @JvmField val afterJob = TrimmingWhen("after-job")
        @JvmField val afterSets = TrimmingWhen("after-sets")
        @JvmField val afterSheets = TrimmingWhen("after-sheets")
        @JvmField val Encoder = KeywordType.encoderOf(TrimmingWhen::class.java) { value, _, _ ->
            TrimmingWhen(value)
        }
    }
}
