// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "uri-security-supported" keyword as defined in:
 *   * [RFC8011](http://www.iana.org/go/rfc8011)
 */
data class UriSecurity(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [UriSecurity] attributes */
    class Type(name: String) : KeywordType<UriSecurity>(Encoder, name)

    companion object {
        @JvmField val none = UriSecurity("none")
        @JvmField val ssl3 = UriSecurity("ssl3")
        @JvmField val tls = UriSecurity("tls")
        @JvmField val Encoder = KeywordType.encoderOf(UriSecurity::class.java) { value, _, _ ->
            UriSecurity(value)
        }
    }
}
