// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.Keyword
import com.hp.jipp.encoding.KeywordType

/**
 * "which-jobs" keyword as defined in
 * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf),
 * [PWG5100.18](http://ftp.pwg.org/pub/pwg/candidates/cs-ippinfra10-20150619-5100.18.pdf),
 * [RFC8011](http://www.iana.org/go/rfc8011).
 *
 * Also used by:
 *   * `which-jobs-supported`
 */
data class WhichJobs(
    override val value: String
) : Keyword() {

    override fun toString() = value

    /** An attribute type for [WhichJobs] attributes */
    class Type(name: String) : KeywordType<WhichJobs>(Encoder, name)

    companion object {
        @JvmField val aborted = WhichJobs("aborted")
        @JvmField val all = WhichJobs("all")
        @JvmField val canceled = WhichJobs("canceled")
        @JvmField val completed = WhichJobs("completed")
        @JvmField val fetchable = WhichJobs("fetchable")
        @JvmField val notCompleted = WhichJobs("not-completed")
        @JvmField val pending = WhichJobs("pending")
        @JvmField val pendingHeld = WhichJobs("pending-held")
        @JvmField val processing = WhichJobs("processing")
        @JvmField val processingStopped = WhichJobs("processing-stopped")
        @JvmField val proofPrint = WhichJobs("proof-print")
        @JvmField val saved = WhichJobs("saved")
        @JvmField val Encoder = KeywordType.encoderOf(WhichJobs::class.java) { value, _, _ ->
            WhichJobs(value)
        }
    }
}
